### ISSUE TITLE
PlayerPickUpEvent triggers system.reflection.ambiguousmatchexception

### ISSUE THREAD

**Issue by MonzUn** [EcoModsDevelopers/Asphalt-ModKit#44]
In the attached project there are several event listeners that aren't working as the trigger system.reflection.ambiguousmatchexception when they are registered. I've dug into the issue a bit but I'm not coming up with much except that I think it's a bug in Asphalt as the types sent in to the function that is throwing the exception is not the types I'm creating (I'm fairly sure).

The only thing that matters in the function definitions is the parameter so it's hard to avoid these exceptions as well.

The project *should* be possibel to just compile after adding the Eco DLLs in Dependencies/Eco (Not allowed to distribute those DLLs)

Feel free to ask me questions about this or ask me to test stuff, either here or on Discord. I'm using the same name in the official Eco Discord so I should be fairly easy to find :)

[EcoAntiGriefingPlugin.zip](https://github.com/EcoModsDevelopers/Asphalt-ModKit/files/4327086/EcoAntiGriefingPlugin.zip)

**Comment by Kronnox** [comment]
Thanks for the heads up and sorry for the long responsetime. This project isn't really maintained anymore; still it's used widely among the Eco community, so I'll probably update it every now and then.

The issue is already resolved. I'm currently fixing all of the other events before releasing a new version. Should be up within the next days
